### ISSUE TITLE
Crash on new project creation

### ISSUE THREAD

**Issue by parsyval** [angular-klingon/klingon#23]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
### Versions.
'@klingon/core': '0.1.0',
  npm: '6.0.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' 

### Repro steps.
Create new project: 
Set name
change prefixe
select in advance options :
- Adds more details to output logging
- Should create a minimal app
- Generate a routing module
Click create

### The log given by the failure.
Error: Unable to start terminal process: CreateProcess failed
    at new WindowsPtyAgent (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\node-pty\lib\windowsTerminal.js:45:23)
    at Object.spawn (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\node-pty\lib\index.js:27:12)
    at app.post (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\terminal.js:23:22)
    at Layer.handle [as handle_request] (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Workspace\PERSO\OSS\klingon\packages\klingon-server\node_modules\express\lib\router\index.js:335:12)
<<< [ 'new',
  'Klingon',
  'Test',
  '--prefix=kli',
  '--source-dir=src',
  '--style=css',
  '--verbose=true',
  '--inline-style=false',
  '--inline-template=false',
  '--dry-run=false',
  '--minimal=true',
  '--routing=true',
  '--skip-commit=false',
  '--skip-git=false',
  '--skip-install=false',
  '--skip-tests=false',
  '' ]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ng ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @klingon/server@0.2.0 start: `node terminal.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @klingon/server@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\parsy.v\AppData\Roaming\npm-cache\_logs\2018-08-30T11_42_41_489Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @klingon/core@0.1.0 start:server: `cd packages/klingon-server/ && npm start`
npm ERR! Exit status 1

### Mention any other details that might be useful.
OS : windows 10

**Comment by sumitparakh** [comment]
1) Error: Unable to start terminal process: CreateProcess failed
> Make sure you have run npm install for klingon-server package.
> replaced  waseemchegham's workspace path by yours in cwd parameter

2) Error: spawn ng ENOENT
> in windows, you will have to replace "ng" by "ng.cmd" as it is unable to recognize ng command without extension.

Try above steps and see if it helps.

**Comment by itswisdomagain** [comment]
Cause: The klingon-server executes ng instructions from a non-existent base directory (/Users/wassimchegham/Sandbox/oss/klingon-workspace)

I'm working on a fix that allows you to specify the root directory for new projects in the klingon-ui and the klingon-app. If this root directory is not specified, the server defaults to the user's home directory.
